title: TuBTLE
subtitle: Tufte Blog Theme with Latex-like Elements
author: Sizhe Liu
simple_search: http://google.com/search
description: A Jekyll theme for content-rich latex-like sites
name: tufte
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:title
timezone: America/Chicago
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/lonitch.github.com/
